title: Hyunwoo Kim
url: "https://hyunwoo.me"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-139322329-1

# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
- name: "Projects"
   link: "projects"
#  - name: "Resume"
#    link: "resume.pdf"

